app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('chamados.urls')),
    path('', include('clientes.urls')),
    path('', include('tecnicos.urls')),

    path('api/v1/', include('authentication.urls')),
]

tecnicos/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path
from . import views

urlpatterns = [
    path('tecnicos/', views.TecnicosList.as_view(), name='tecnicos_list'),
    path('tecnicos/create/', views.TecnicosCreate.as_view(), name='tecnicos_create'),
    path('tecnicos/<int:pk>/detail/', views.TecnicosDetail.as_view(), name='tecnicos_detail'),
    path('tecnicos/<int:pk>/update/', views.TecnicosUpdate.as_view(), name='tecnicos_update'),
    path('tecnicos/<int:pk>/delete/', views.TecnicosDelete.as_view(), name='tecnicos_delete'),

]

tecnicos/models.py
from django.db import models
from clientes.models import Estado, Cidade, Bairro, Nivel, StatusClientes
    
class FormacaoTecnico(models.Model):
    nome = models.CharField(max_length=200)
    class Meta:
        ordering = ['nome']
    def __str__(self):
        return self.nome


class Tecnicos(models.Model):
    nome = models.CharField(max_length=200)
    data_nascimento = models.DateField()
    rg = models.CharField(null=True, blank=True, default=0)
    cpf = models.CharField(max_length=14)
    endereco = models.CharField(max_length=200)
    estado = models.ForeignKey(Estado, on_delete=models.PROTECT, related_name='estado_tecnicos')
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT, related_name='cidade_tecnicos')
    bairro = models.ForeignKey(Bairro, on_delete=models.PROTECT, related_name='bairro_tecnicos')
    cep = models.CharField(max_length=20)
    telefone = models.CharField(max_length=200)
    formacao = models.ForeignKey(FormacaoTecnico, on_delete=models.PROTECT, related_name='formacao_tecnicos')
    status = models.ForeignKey(StatusClientes, on_delete=models.PROTECT, related_name='status_tecnicos')
    nivel = models.ForeignKey(Nivel, on_delete=models.PROTECT, related_name='nivel_tecnicos')
    n3 = models.IntegerField(null=True, blank=True, default=0)
    n2 = models.IntegerField(null=True, blank=True, default=0)
    n1 = models.IntegerField(null=True, blank=True, default=0)
    observacao = models.CharField(max_length=200, null=True, blank=True)
        
    class Meta:
        ordering = ['nome']
        
    def __str__(self):
        return self.nome

tecnicos/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import models
from . import form
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages


# Create your views here.
class TecnicosList(LoginRequiredMixin, ListView):
    model = models.Tecnicos
    template_name = 'tecnicos_list.html'
    context_object_name = 'tecnicos'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        nome_tecnico = self.request.GET.get('nome')

        if nome_tecnico:
            queryset = queryset.filter(nome__icontains=nome_tecnico)

        return queryset

class TecnicosCreate(LoginRequiredMixin, CreateView):
    model = models.Tecnicos
    template_name = 'tecnicos_create.html'
    form_class = form.TecnicosForm
    success_url = reverse_lazy('tecnicos_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Técnico cadastrado com sucesso!')
        return response

class TecnicosDetail(LoginRequiredMixin, DetailView):
    model = models.Tecnicos
    template_name = 'tecnicos_details.html'

class TecnicosUpdate(LoginRequiredMixin, UpdateView):
    model = models.Tecnicos
    template_name = 'tecnicos_update.html'
    form_class = form.TecnicosForm
    success_url = reverse_lazy('tecnicos_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Dados do tecnico atualizados com sucesso!')
        return response    
    
class TecnicosDelete(LoginRequiredMixin, DeleteView):
    model = models.Tecnicos
    template_name = 'tecnicos_delete.html'
    success_url = reverse_lazy('tecnicos_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Técnico excluído com sucesso!')
        return response

tecnicos/templates/tecnicos_create.html
{% extends "base.html" %}
{% block content %}

<!-- jQuery (obrigatório para o plugin funcionar) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- jQuery Mask Plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

<script>
  $(document).ready(function(){
    $('#id_cpf').mask('000.000.000-00');  // Aplica máscara no campo com id "id_cpf"
    $('#id_cep').mask('00.000-000');
    $('#id_telefone').mask('(00)00000-0000');
    $('#id_rg').mask('00.000.000-0');
  });
</script>


<div class="container d-flex align-items-center justify-content-center min-vh-100">
  <div class="w-100" style="max-width: 600px;">
  <h3>Cadastro de Tecnicos</h3>
      <div class="card">
        <div class="card-body">
          <form method="POST" class="form-control" action="">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Cadastrar Tecnico</button>
              <a href="{% url 'tecnicos_list' %}" class="btn btn-danger">Cancelar</a>
          </form>
        </div>
        </div>
        
      </div>
    </div>
  </div>

{% endblock %}

tecnicos/templates/tecnicos_delete.html
{% extends "base.html" %}
{% block content %}

<div class="container d-flex align-items-center justify-content-center min-vh-100">
  <div class="w-100" style="max-width: 600px;">
  <h3>Exclusão de Téncicos</h3>
      <div class="card">
        <div class="card-body">
          <p class="card-text">Tem certeza que deseja excluir o Técnico <strong>{{ object.nome }}</strong>?</p>
          <form method="POST" class="form-control" action="">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Deletar</button>
              <a href="{% url 'tecnicos_list' %}" class="btn btn-primary">Cancelar</a>
          </form>
        </div>
        </div>
        
      </div>
    </div>
  </div>

{% endblock %}

tecnicos/templates/tecnicos_details.html
{% extends "base.html" %}
{% block content %}

<div class="container d-flex align-items-center justify-content-center min-vh-100">
  <div class="w-100" style="max-width: 600px;">
  <h3>Informações do Técnico</h3>
      <div class="card">
        <div class="card-body">
          <div>
          <table class="table table-striped table-bordered">
            <thead class="thead-dark">
              <tr>
                <th>Técnico</th>
                <th>Dados</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>Nome</th>
                <td>{{object.nome}}</td>
              </tr>
              <tr>
                <th>Data de Nascimento</th>
                <td>{{object.data_nascimento}}</td>
              </tr>
              <tr>
                <th>RG</th>
                <td>{{object.rg}}</td>
              </tr>
              <tr>
                <th>CPF</th>
                <td>{{object.cpf}}</td>
              </tr>
              <tr>
                <th>Endereço</th>
                <td>{{object.endereco}}</td>
              </tr>
              <tr>
                <th>Estado</th>
                <td>{{object.estado}}</td>
              </tr>
              <tr>
                <th>Cidade</th>
                <td>{{object.cidade}}</td>
              </tr>
              <tr>
                <th>Bairro</th>
                <td>{{object.bairro}}</td>
              </tr>
              <tr>
                <th>CEP</th>
                <td>{{object.cep}}</td>
              </tr>
              <tr>
                <th>Telefone</th>
                <td>{{object.telefone}}</td>
              </tr>
              <tr>
                <th>Formação</th>
                <td>{{object.formacao}}</td>
              </tr>
              <tr>
                <th>Status</th>
                <td>{{object.status}}</td>
              </tr>
              <tr>
                <th>Nível</th>
                <td>{{object.nivel}}</td>
              </tr>
              <tr>
                <th>Chamados Nível 3</th>
                <td>{{object.n3}}</td>
              </tr>
              <tr>
                <th>Chamados Nível 2</th>
                <td>{{object.n2}}</td>
              </tr>
              <tr>
                <th>Chamados Nível 1</th>
                <td>{{object.n1}}</td>
              </tr>
              <tr>
                <th>Observação</th>
                <td>{{object.observacao}}</td>
              </tr>
            </tbody>
          </table>
          </div>
  
        </div>
        <br>
        <a href="{% url 'tecnicos_list' %}" class="btn btn-danger">Voltar</a>
        
      </div>
    </div>

{% endblock %}

tecnicos/templates/tecnicos_list.html
{% extends "base.html" %}
{% block content %}

  <h3>Tecnicos</h3>
  <div class="row mb-3">
    <div class="col-md-6">
      <form method="get" action="{% url 'tecnicos_list' %}">
        <div class="input-group">
          <input type="text" class="form-control" name="nome" placeholder="Nome do Técnicos" value="{{ request.GET.nome }}">
          <button type="submit" class="btn btn-success">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </form>
    </div>
  <div class="col-md-6">
    <a href="{% url 'tecnicos_create' %}" class="btn btn-success">
      <i class="bi bi-plus"></i> Cadastrar Técnico
    </a>
  </div>
  </div>
    <div>
    <table class="table table-striped table-bordered">
      <thead class="thread-dark">
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">CPF</th>
          <th scope="col">Data de Nascimento</th>
          <th scope="col">UF</th>
          <th scope="col">Cidade</th>
          <th scope="col">Bairro</th>
          <th scope="col">Telefone</th>
          <th scope="col">Status</th>
          <th scope="col">Nível</th>
          <th scope="col">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for tecnico in tecnicos  %}
        <tr>
          <td>{{ tecnico.nome }}</td>
          <td>{{ tecnico.cpf }}</td>
          <td>{{ tecnico.data_nascimento }}</td>
          <td>{{ tecnico.estado }}</td>
          <td>{{ tecnico.cidade }}</td>
          <td>{{ tecnico.bairro }}</td>
          <td>{{ tecnico.telefone }}</td>
          <td>{{ tecnico.status }}</td>
          <td>{{ tecnico.nivel }}</td>   
          <td>
            <a href="{% url 'tecnicos_detail' tecnico.id %}" class="btn btn-primary">
              <i class="bi bi-eye"></i>
            </a>
            <a href="{% url 'tecnicos_update' tecnico.id %}" class="btn btn-success">
              <i class="bi bi-pencil-square"></i>
            </a>
            <a href="{% url 'tecnicos_delete' tecnico.id %}" class="btn btn-danger">
              <i class="bi bi-trash-fill"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>

{% include 'components/pagination.html' %}

{% endblock %}

tecnicos/templates/tecnicos_update.html
{% extends "base.html" %}
{% block content %}

<!-- jQuery (obrigatório para o plugin funcionar) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- jQuery Mask Plugin -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>

<script>
  $(document).ready(function(){
    $('#id_cpf').mask('000.000.000-00');  // Aplica máscara no campo com id "id_cpf"
    $('#id_cep').mask('00.000-000');
    $('#id_telefone').mask('(00)00000-0000');
    $('#id_rg').mask('00.000.000-0');
  });
</script>

<div class="container d-flex align-items-center justify-content-center min-vh-100">
  <div class="w-100" style="max-width: 600px;">
  <h3>Edição de Tecnicos</h3>
      <div class="card">
        <div class="card-body">
          <form method="POST" class="form-control" action="">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Editar</button>
              <a href="{% url 'clientes_list' %}" class="btn btn-danger">Cancelar</a>
          </form>
        </div>
        </div>
        
      </div>
    </div>
  </div>

{% endblock %}